security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\User\User
        property: email
        manager_name: users

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true

    main:
      stateless: false
      pattern: ^/
      provider: app_user_provider
      custom_authenticators:
        - App\Security\GoogleAuthenticator
      entry_point: App\Security\GoogleAuthenticator

      logout:
        path: app_logout
        target: /

  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/preview, roles: [ROLE_USER, ROLE_ADMIN] }
    - { path: ^/checker, roles: [ROLE_USER, ROLE_ADMIN] }
    - { path: ^/dc, roles: [ROLE_USER, ROLE_ADMIN] }
