connect_google_start:
  path: /connect/google
  controller: App\Controller\OAuthController::connect

connect_google_check:
  path: /connect/google/check
  controller: App\Controller\OAuthController::check
